language: csharp
solution: Proximax.Sirius.Chain.SDK.sln
dist: xenial

matrix:
  include:
    - dotnet: 2.2.104
      mono: none
      script:
       - dotnet build src/ProximaX.Sirius.Chain.Sdk
       - dotnet build src/ProximaX.Sirius.Chain.Sdk.Tests
       - dotnet test src/ProximaX.Sirius.Chain.Sdk.Tests
